# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "manufacture"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "8001:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@manfacture.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres


networks:
  postgres:
    driver: bridge